### PR TITLE
feat(util): add converter from array buffer to string

### PR DESCRIPTION
**Pull request by maasencioh**

### CODE REVIEW

**Comment by targos** [comment]
What is it for?

**Comment by targos** [comment]
It's probably easier and more efficient to use the Blob API

**Comment by maasencioh** [comment]
I have to use this a lot in the visualizer, to parse from ArrayBuffer to string, how could you use the Blob API instead?

**Comment by targos** [comment]
I'm worried why you have to use it a lot? Do you have a concrete example?

**Comment by maasencioh** [comment]
When I'm uploading a file into the drag and drop to display a chromatogram I will like to parse from a text  (like JCAMP) or a file (like NetCDF), so I need to parse from one to the other very commonly

**Comment by targos** [comment]
You should use a different read type for each kind of file in the drag and drop module.
Something like this: 
image

**Pull request closed without merging**
