### PR TITLE
calculate OCL index when molecule changes

### PR DESCRIPTION
**Pull request by targos**

### CODE REVIEW

**Comment by stropitek** [comment]
@lpatiny

**Comment by lpatiny** [comment]
LGTM but we should take care about what we export in the getToc because as usual the chemist wants to see the molecule the way he drew it and the getToc is not designed for substructure search (there is a special view for this as far as I know).

https://github.com/cheminfo/roc-eln-config/blob/master/getToc.js

For me the getToc should return a oclID like
```
oclid: {
value: xxx,
coordinates: yyy
}
```

**Comment by lpatiny** [comment]
Here is the TOC of EPFL
https://github.com/cheminfo/eln.epfl.ch/blob/master/rest-on-couch-home/eln/getToc.js
And this should be changed if the index is put at the same level of oclid so that this property does not end up in the toc

**Comment by stropitek** [comment]
The special view was created because calculating the view could take a long time when using OCL. This is no longer an issue if the ocl attributes are in the document

this [getToc](https://github.com/cheminfo/roc-eln-config/blob/master/getToc.js)  is already including ocl attributes

**Comment by targos** [comment]
We don't need the index in getToc, but we need the coordinates. I think it's better to do this:

```diff
23,24c23
<         oclid: general.ocl && general.ocl.value,
<         index: general.ocl && general.ocl.index,
---
>         oclid: general.ocl && {value: general.ocl.value, coordinates: general.ocl.coordinates},

```

**Comment by stropitek** [comment]
ok, agreed. And the substructure search view would have the index attribute added to it

**Comment by lpatiny** [comment]
Probably the index should not be at the level of oclID and oclID should still be code + coordinates. Really the chemists like to see the molecule the way they drew it.

**Comment by targos** [comment]
the index can technically be at the level of the the ID. Why not do it?

**Comment by lpatiny** [comment]
ok

**Pull request merged**
